src/lib.ts
When aggregating pubkeys and signatures the first point is used as aggregate to add to, but it's not cloned causing mutation. If that point is used afterwards it will no longer hold the expected key potentially causing valid signatures to be checked as invalid
=> Fix point mutation on aggregate

test/multithread/naive/naive.test.ts
TODO: tiny-workers in windows NodeJS v10 is not able to serialize Buffers properly and reach the worker broken
=> Skip multi-thread test for node < 12

benchmark/batchVerify.ts, benchmark/index.ts, benchmark/multithread.ts, benchmark/multithreadOverhead.ts, benchmark/runner.ts, src/lib.ts, test/lib/index.test.ts, test/multithread/naive/index.ts, test/multithread/naive/naive.test.ts, test/multithread/naive/worker.ts
Points are represented in two ways in BLST:
- affine coordinates (x,y)
- jacobian coordinates (x,y,z)
The jacobian coordinates allow to aggregate points more efficiently, so if P1 points are aggregated often (Eth2.0) you want to keep the point cached in jacobian coordinates.
---
The PublicKey class becomes a wrapper for P1 points in both coordinates representations. Internal point may be represented in affine or jacobian coordinates.
This approach allows to use this wrapper very flexibly while minimizing the coordinate conversions if used properly.
To force a instance of PublicKey to permanently switch its coordType
```ts
const pkAsAffine = new PublicKey(pk.affine)
```
=> Re-org lib

src/lib.ts
Avoids using a zero multiplier for a signature in batch verification.
Fixes https://github.com/ChainSafe/blst-ts/issues/45
=> Avoid zero batch multiplier

src/scripts/downloadReleaseAsset.ts, src/scripts/testBindings.ts
- split the install script in two pieces (using prebuilt bindings and building fresh bindings)
- fix download script to await the downloaded file
=> Use child processes in install script

.github/workflows/main.yml
**Motivation**
- v0.2.7 was build with ubuntu 22.04 and it caused https://github.com/ChainSafe/blst-ts/issues/78
- See https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
**Description**
- Switch back to ubuntu 20.04 to create binding files like in v0.2.6 which works fine everywhere
Closes #78
=> Use ubuntu 20.04 to build binding files

README.md, package.json, test/spec/downloadTests.ts, tsconfig.json, yarn.lock
In addressing https://github.com/ChainSafe/blst-ts/issues/80 I realize the spec tests can't be downloaded on Mac OS,  rather than using a shell script that uses [wget](https://www.gnu.org/software/wget/) we really should be more OS agnostic and utilize the node environment libs
=> Fix: Added more cross-platform script to downloaded spec tests

src/lib.ts
Replaces the call to `isZeroBytes` with `cypto.timingSafeEqual` to achieve constant time comparison to empty buffer.
=> fix: SecretKey.fromBytes perform constant time comparison to zero bytes

rebuild/.eslintrc.cjs, rebuild/.mocharc.cjs, rebuild/.mocharc.yaml, rebuild/lib/index.d.ts, rebuild/lib/index.js, rebuild/package.json, rebuild/src/addon.cc, rebuild/src/functions.cc, rebuild/src/public_key.cc, rebuild/src/secret_key.cc, rebuild/src/signature.cc, rebuild/test/__fixtures__/index.ts, rebuild/test/spec/downloadTests.ts, rebuild/test/spec/index.test.ts, rebuild/test/spec/specTestVersioning.ts, rebuild/test/types.ts, rebuild/test/unit/PublicKey.test.ts, rebuild/test/unit/SecretKey.test.ts, rebuild/test/unit/Signature.test.ts, rebuild/test/unit/aggregatePublicKeys.test.ts, rebuild/test/unit/aggregateSignatures.test.ts, rebuild/test/unit/bindings.test.ts, rebuild/test/unit/verify.test.ts, rebuild/test/unit/verifyMultipleAggregateSignatures.test.ts, rebuild/test/utils.ts, rebuild/tsconfig.json
- Add `toHex` method to `SecretKey`, `PublicKey` and `Signature`
- Convert to esmodule
- Add `default` export
- Rename msg->message in SignatureSet
- Lint files
=> feat(rebuild): fixes from implementation into lodestar

rebuild/.eslintrc.cjs, rebuild/.mocharc.cjs, rebuild/.mocharc.yaml, rebuild/lib/index.d.ts, rebuild/lib/index.js, rebuild/package.json, rebuild/src/addon.cc, rebuild/src/addon.h, rebuild/src/functions.cc, rebuild/src/public_key.cc, rebuild/src/secret_key.cc, rebuild/src/signature.cc, rebuild/test/__fixtures__/index.ts, rebuild/test/spec/downloadTests.ts, rebuild/test/spec/index.test.ts, rebuild/test/spec/specTestVersioning.ts, rebuild/test/types.ts, rebuild/test/unit/PublicKey.test.ts, rebuild/test/unit/SecretKey.test.ts, rebuild/test/unit/Signature.test.ts, rebuild/test/unit/aggregatePublicKeys.test.ts, rebuild/test/unit/aggregateSignatures.test.ts, rebuild/test/unit/bindings.test.ts, rebuild/test/unit/verify.test.ts, rebuild/test/unit/verifyMultipleAggregateSignatures.test.ts, rebuild/test/utils.ts, rebuild/tsconfig.json
Add spec tests for the rebuild folder
- rebuild/test/spec folder
- add `BLST_ERROR:` prefix to all errors for catch in spec test
=> test(rebuild): add spec tests

rebuild/.eslintrc.js, rebuild/lib/index.d.ts, rebuild/lib/index.js, rebuild/lib/index.mjs, rebuild/package.json, rebuild/test/__fixtures__/index.ts, rebuild/test/spec/downloadTests.ts, rebuild/test/spec/index.test.ts, rebuild/test/spec/specTestVersioning.ts, rebuild/test/types.ts, rebuild/test/unit/PublicKey.test.ts, rebuild/test/unit/SecretKey.test.ts, rebuild/test/unit/Signature.test.ts, rebuild/test/unit/aggregatePublicKeys.test.ts, rebuild/test/unit/aggregateSignatures.test.ts, rebuild/test/unit/bindings.test.ts, rebuild/test/unit/verify.test.ts, rebuild/test/unit/verifyMultipleAggregateSignatures.test.ts, rebuild/test/utils.ts, rebuild/tsconfig.json, rebuild/yarn.lock, tsconfig.json
There were challenges testing the new and old code together with different module types.  This can be switched back to pure es6 modules in the future if necessary but is now built as dual module setup.
**NOTE: There are no code changes.  Only config and import statement updates**
=> feat: convert rebuild folder to cjs/mjs setup

.github/workflows/main.yml
A new [macos runner](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) has been released. This image runs on M1 architecture, allowing to create `prebuilds` for `darwin/arm64`.
=> chore: add darwin/arm64 prebuild support

src/lib.ts
Properly check all bytes for zeroes.
Also `export` the function so that it can be reused.
=> fix: correctly check random bytes

rebuild/lib/index.d.ts, rebuild/src/public_key.cc, rebuild/src/public_key.h, rebuild/src/signature.cc, rebuild/src/signature.h, src/lib.ts, test/perf/multithreading.test.ts, test/utils/multithreading/blsMultiThreading.ts, test/utils/multithreading/queuedJob.ts, test/utils/multithreading/types.ts
Perf Results
```sh
multithreading perf - addVerificationRandomness true
✓ libuv multithreading - napi - addVerificationRandomness true       0.2730140 ops/s    3.662816  s/op        -         12 runs   47.7 s
✓ worker multithreading - swig - addVerificationRandomness true      0.2128583 ops/s    4.697962  s/op        -         12 runs   61.0 s
{ libuvPoolSize: 9, workerPoolSize: 9 }
multithreading perf - addVerificationRandomness false
✓ libuv multithreading - napi - addVerificationRandomness false      0.2842713 ops/s    3.517767  s/op        -         12 runs   45.7 s
✓ worker multithreading - swig - addVerificationRandomness false     0.2274196 ops/s    4.397158  s/op        -         12 runs   57.2 s
{ libuvPoolSize: 9, workerPoolSize: 9 }
```
=> feat: add MultiplyBy

rebuild/binding.gyp, rebuild/src/addon.cc, rebuild/src/addon.h, rebuild/src/functions.cc, rebuild/src/functions.h, rebuild/src/public_key.cc, rebuild/src/public_key.h, rebuild/src/secret_key.cc, rebuild/src/secret_key.h, rebuild/src/signature.cc, rebuild/src/signature.h
@LesnyRumcajs I moved all the commits with changes here because that branch cannot get merged like what you see and I could not update the base and target branches.  I will continue to respond to all changes in that PR and the commits will go here onto this branch so the merge happens correctly
=> fix: addressing Huberts PR comments

.github/workflows/main.yml, package.json, scripts/makeRelease.ts, test/fuzz/fuzz.test.ts, test/unit/PublicKey.test.ts, test/unit/aggregatePublicKeys.test.ts, yarn.lock
**Description**
I updated the actions/upload-artifacts and actions/download-artifacts and the API changed slightly so it didn't work the way it used to in the old workflow.
There were a couple of other small things that I noticed during publishing
- tested the package that gets published and needed to add types back in to get working in `@chainsafe/bls`
- remove `@jazzer.js/core` from optionalDependencies to stop it from getting installed by dependent packages
- add `@jazzer.js/core` in fuzz test on the fly on first run
- there is a 1 in 100 fail on unit test.  the error message returned from supranational/blst changes in rare instances.  There is still an error thrown, its just the error message that gets check by unit test changes from `BLST_POINT_NOT_ON_CURVE` to `BLST_BAD_ENCODING`
=> fix: update workflow for new actions version

lib/index.d.ts, lib/index.js, src/addon.h, src/secret_key.cc, test/unit/PublicKey.test.ts, test/unit/SecretKey.test.ts, test/unit/Signature.test.ts
@nflaig pointed out that the return types are buffer not uint8array.  Putting this up in case we should move to uint8array.
After this and the `bls` package are published remove this cast in lodestar tests
https://github.com/ChainSafe/lodestar/pull/6616#discussion_r1567948604
=> feat: make serialized objects Uint8Array instead of Buffer

src/addon.cc, src/addon.h, src/functions.cc
Caught an issue with verification
Ensure rand bytes are never all 0.
Was originally like this in the old blst
https://github.com/ChainSafe/blst-ts/blob/b1ba6333f664b08e5c50b2b0d18c4f079203962b/src/lib.ts#L288
=> feat: make sure random bytes are non-zero

src/functions.cc
Conver num_bytes to num_bits in `mul_n_aggregate` call
=> fix: bug in verifyMultipleAggregateSignatures

package.json, scripts/dev.ts, scripts/install.ts, src/addon.h, src/functions.cc, src/public_key.cc, src/secret_key.cc, src/secret_key.h, src/signature.cc
**Motivations**
When doing the aggregate with randomness PR I noticed a couple of small issues.  In particular the workflow was downloading the bindings with the install command instead of building the new version of the code and unit tests were failing because the new feature was not available in the bindings.
This needs to be handled first so I moved the other small changes over to here for clarity and separation of concerns.
**Description of Changes**
- Update install script to check for `process.env.CI` or `process.env.BLST_TS_FORCE_BUILD` to enforce building of bindings
- Fix `scripts/dev` command (leftover from merging code to master and first time running since)
- Clean up usage of `using std::string_literals`
- Clean up header includes
- Lint code
=> fix: small issues post merge

Dockerfile, package.json
Trigger publish of 1.0.1.  Will unpublish 1.0.0 for security reasons after this is merged and released
Also has small fix of CI.  Was done for regular build but the ENV variable did not make it into the build containers for the linux-arm64 builds so need to manually pass add it to the `Dockerfile`
https://github.com/ChainSafe/blst-ts/pull/140
=> chore: publish 1.0.1

src/public_key.cc, src/signature.cc
When implementing aggregateWithRandomness I found this bug.  Is same as the mult verification bits vs bytes error and can result in invalid verification returning as valid.
=> fix: bits vs bytes in multiplyBy

npm/darwin-arm64/package.json, npm/darwin-x64/package.json, npm/linux-arm64-gnu/package.json, npm/linux-arm64-musl/README.md, npm/linux-arm64-musl/package.json, npm/linux-x64-gnu/package.json, npm/linux-x64-musl/README.md, npm/linux-x64-musl/package.json, npm/win32-x64-msvc/package.json, package.json
- Adds linux-musl triples for arm64 and x64 
- Bumps version to publish
=> chore: add linux musl build

index.d.ts, index.js, src/lib.rs, test/unit/aggregateWithRandomness.test.ts, test/unit/bindings.test.ts
Add async version of aggregate_with_randomness.  See https://github.com/ChainSafe/lodestar/issues/7197 for more info regarding why this is important
=> feat: add asyncAggregateWithRandomness
